import tkinter as tk
from db_query import Database

db=Database('appni.db')

username = tk.StringVar()
password = tk.StringVar()
app_id = tk.StringVar()
consumer_key = tk.StringVar()
access_token = tk.StringVar()

nft_lvl=tk.IntVar()
bnf_lvl=tk.IntVar()

n_ce_side=tk.StringVar()
n_ce_strk_var=tk.IntVar()
n_ce_entry=tk.StringVar()
n_ce_stop=tk.StringVar()
n_ce_max_try=tk.IntVar()
n_ce_qnty=tk.IntVar()
n_ce_spot_level=tk.IntVar()
n_ce_active=tk.IntVar()

n_pe_side=tk.StringVar()
n_pe_strk_var=tk.IntVar()
n_pe_entry=tk.StringVar()
n_pe_stop=tk.StringVar()
n_pe_max_try=tk.IntVar()
n_pe_qnty=tk.IntVar()
n_pe_spot_level=tk.IntVar()
n_pe_active=tk.IntVar()

bn_ce_active=tk.IntVar()
bn_ce_side=tk.StringVar()
bn_ce_strk_var=tk.IntVar()
bn_ce_entry=tk.StringVar()
bn_ce_stop=tk.StringVar()
bn_ce_max_try=tk.IntVar()
bn_ce_qnty=tk.IntVar()
bn_ce_spot_level=tk.IntVar()
bn_ce_active=tk.IntVar()

bn_pe_side=tk.StringVar()
bn_pe_strk_var=tk.IntVar()
bn_pe_entry=tk.StringVar()
bn_pe_stop=tk.StringVar()
bn_pe_max_try=tk.IntVar()
bn_pe_qnty=tk.IntVar()
bn_pe_spot_level=tk.IntVar()
bn_pe_active=tk.IntVar()

username.set(db.fetch_user()[1])
password.set(db.fetch_user()[2])
app_id.set(db.fetch_user()[3])
consumer_key.set(db.fetch_user()[4])
access_token.set(db.fetch_user()[5])

nft_lvl.set(db.fetch('NIFTY_CE')[8])
bnf_lvl.set(db.fetch('BANKNIFTY_CE')[8])

n_ce_side.set(db.fetch('NIFTY_CE')[2])
n_ce_strk_var.set(db.fetch('NIFTY_CE')[3])
n_ce_entry.set(db.fetch('NIFTY_CE')[4])
n_ce_stop.set(db.fetch('NIFTY_CE')[5])
n_ce_max_try.set(db.fetch('NIFTY_CE')[6])
n_ce_qnty.set(db.fetch('NIFTY_CE')[7])
n_ce_spot_level.set(db.fetch('NIFTY_CE')[8])
n_ce_active.set(db.fetch('NIFTY_CE')[9])

n_pe_side.set(db.fetch('NIFTY_PE')[2])
n_pe_strk_var.set(db.fetch('NIFTY_PE')[3])
n_pe_entry.set(db.fetch('NIFTY_PE')[4])
n_pe_stop.set(db.fetch('NIFTY_PE')[5])
n_pe_max_try.set(db.fetch('NIFTY_PE')[6])
n_pe_qnty.set(db.fetch('NIFTY_PE')[7])
n_pe_spot_level.set(db.fetch('NIFTY_PE')[8])
n_pe_active.set(db.fetch('NIFTY_PE')[9])

bn_ce_side.set(db.fetch('BANKNIFTY_CE')[2])
bn_ce_strk_var.set(db.fetch('BANKNIFTY_CE')[3])
bn_ce_entry.set(db.fetch('BANKNIFTY_CE')[4])
bn_ce_stop.set(db.fetch('BANKNIFTY_CE')[5])
bn_ce_max_try.set(db.fetch('BANKNIFTY_CE')[6])
bn_ce_qnty.set(db.fetch('BANKNIFTY_CE')[7])
bn_ce_spot_level.set(db.fetch('BANKNIFTY_CE')[8])
bn_ce_active.set(db.fetch('BANKNIFTY_CE')[9])

bn_pe_side.set(db.fetch('BANKNIFTY_PE')[2])
bn_pe_strk_var.set(db.fetch('BANKNIFTY_PE')[3])
bn_pe_entry.set(db.fetch('BANKNIFTY_PE')[4])
bn_pe_stop.set(db.fetch('BANKNIFTY_PE')[5])
bn_pe_max_try.set(db.fetch('BANKNIFTY_PE')[6])
bn_pe_qnty.set(db.fetch('BANKNIFTY_PE')[7])
bn_pe_spot_level.set(db.fetch('BANKNIFTY_PE')[8])
bn_pe_active.set(db.fetch('BANKNIFTY_PE')[9])