import tkinter as tk

username = tk.StringVar()
password = tk.StringVar()
app_id = tk.StringVar()
consumer_key = tk.StringVar()
access_token = tk.StringVar()
cancel_order_id = tk.StringVar()

nft_lvl=tk.IntVar()
bnf_lvl=tk.IntVar()

n_ce_side=tk.StringVar()
n_ce_strk_var=tk.IntVar()
n_ce_entry=tk.StringVar()
n_ce_stop=tk.StringVar()
n_ce_max_try=tk.IntVar()
n_ce_qnty=tk.IntVar()
n_ce_spot_level=tk.IntVar()
n_ce_active=tk.IntVar()

n_pe_side=tk.StringVar()
n_pe_strk_var=tk.IntVar()
n_pe_entry=tk.StringVar()
n_pe_stop=tk.StringVar()
n_pe_max_try=tk.IntVar()
n_pe_qnty=tk.IntVar()
n_pe_spot_level=tk.IntVar()
n_pe_active=tk.IntVar()

bn_ce_active=tk.IntVar()
bn_ce_side=tk.StringVar()
bn_ce_strk_var=tk.IntVar()
bn_ce_entry=tk.StringVar()
bn_ce_stop=tk.StringVar()
bn_ce_max_try=tk.IntVar()
bn_ce_qnty=tk.IntVar()
bn_ce_spot_level=tk.IntVar()
bn_ce_active=tk.IntVar()

bn_pe_side=tk.StringVar()
bn_pe_strk_var=tk.IntVar()
bn_pe_entry=tk.StringVar()
bn_pe_stop=tk.StringVar()
bn_pe_max_try=tk.IntVar()
bn_pe_qnty=tk.IntVar()
bn_pe_spot_level=tk.IntVar()
bn_pe_active=tk.IntVar()